const jobs = [
    {
      id: '1',
      title: 'Web Geliştirici',
      company: 'ABC Teknoloji',
      location: 'İstanbul',
      description: 'React ve Node.js ile web uygulamaları geliştirmek.',
      image: 'https://source.unsplash.com/300x200/?web-development',
      workingHours: 'Belirtilmemiş',
      department: 'Bilgi Teknolojileri',
      workType: 'Tam Zamanlı',
      positionLevel: 'Uzman',
      experience: '3-5 yıl deneyim',
      educationLevel: 'Üniversite(Mezun)'
    },
    {
      id: '2',
      title: 'Veri Analisti',
      company: 'XYZ Veri',
      location: 'Ankara',
      description: 'Büyük veri setleri üzerinde analiz yapmak.',
      image: 'https://source.unsplash.com/300x200/?data-analysis',
      workingHours: 'Haftada 40 saat',
      department: 'Veri Analizi',
      workType: 'Tam Zamanlı',
      positionLevel: 'Uzman',
      experience: '2-3 yıl deneyim',
      educationLevel: 'Üniversite(Mezun)'
    },
    {
      id: '3',
      title: 'Mobil Uygulama Geliştirici',
      company: '123 Mobile',
      location: 'İzmir',
      description: 'iOS ve Android için mobil uygulamalar geliştirmek.',
      image: 'https://source.unsplash.com/300x200/?mobile-app',
      workingHours: 'Belirtilmemiş',
      department: 'Mobil Geliştirme',
      workType: 'Tam Zamanlı',
      positionLevel: 'Uzman',
      experience: '4-6 yıl deneyim',
      educationLevel: 'Üniversite(Mezun)'
    },
    {
      id: '4',
      title: 'Yazılım Mühendisi',
      company: 'Tech Solutions',
      location: 'Bursa',
      description: 'Yüksek performanslı yazılım çözümleri geliştirmek.',
      image: 'https://source.unsplash.com/300x200/?software-engineer',
      workingHours: 'Haftada 40 saat',
      department: 'Yazılım Geliştirme',
      workType: 'Tam Zamanlı',
      positionLevel: 'Uzman',
      experience: '5-7 yıl deneyim',
      educationLevel: 'Üniversite(Mezun)'
    },
    {
      id: '5',
      title: 'Grafik Tasarımcı',
      company: 'Creative Designs',
      location: 'Antalya',
      description: 'Görsel içerikler oluşturmak ve tasarlamak.',
      image: 'https://source.unsplash.com/300x200/?graphic-design',
      workingHours: 'Belirtilmemiş',
      department: 'Grafik Tasarım',
      workType: 'Tam Zamanlı',
      positionLevel: 'Uzman',
      experience: '3-5 yıl deneyim',
      educationLevel: 'Üniversite(Mezun)'
    },
    {
      id: '6',
      title: 'Sistem Analisti',
      company: 'Smart Systems',
      location: 'Adana',
      description: 'Kurumsal sistem ihtiyaçlarını analiz etmek.',
      image: 'https://source.unsplash.com/300x200/?system-analyst',
      workingHours: 'Haftada 40 saat',
      department: 'Sistem Analizi',
      workType: 'Tam Zamanlı',
      positionLevel: 'Uzman',
      experience: '4-6 yıl deneyim',
      educationLevel: 'Üniversite(Mezun)'
    },
    {
      id: '7',
      title: 'Frontend Geliştirici',
      company: 'UI/UX Creators',
      location: 'Eskişehir',
      description: 'Kullanıcı arayüzleri ve deneyimleri geliştirmek.',
      image: 'https://source.unsplash.com/300x200/?frontend-development',
      workingHours: 'Haftada 40 saat',
      department: 'Frontend Geliştirme',
      workType: 'Tam Zamanlı',
      positionLevel: 'Uzman',
      experience: '3-5 yıl deneyim',
      educationLevel: 'Üniversite(Mezun)'
    },
    {
      id: '8',
      title: 'Back-end Geliştirici',
      company: 'Code Masters',
      location: 'Trabzon',
      description: 'Server-side uygulama mantığı ve altyapıları geliştirmek.',
      image: 'https://source.unsplash.com/300x200/?backend-development',
      workingHours: 'Haftada 40 saat',
      department: 'Backend Geliştirme',
      workType: 'Tam Zamanlı',
      positionLevel: 'Uzman',
      experience: '5-7 yıl deneyim',
      educationLevel: 'Üniversite(Mezun)'
    },
    {
      id: '9',
      title: 'Veri Bilimci',
      company: 'Data Insights',
      location: 'Samsun',
      description: 'Büyük veri setleri üzerinde analitik çalışmalar yapmak.',
      image: 'https://source.unsplash.com/300x200/?data-science',
      workingHours: 'Haftada 40 saat',
      department: 'Veri Bilimi',
      workType: 'Tam Zamanlı',
      positionLevel: 'Uzman',
      experience: '3-5 yıl deneyim',
      educationLevel: 'Yüksek Lisans(Mezun)'
    },
    {
      id: '10',
      title: 'UI/UX Tasarımcı',
      company: 'Digital Designs',
      location: 'Gaziantep',
      description: 'Kullanıcı arayüzü ve kullanıcı deneyimi tasarımları yapmak.',
      image: 'https://source.unsplash.com/300x200/?ui-ux-design',
      workingHours: 'Belirtilmemiş',
      department: 'UI/UX Tasarım',
      workType: 'Tam Zamanlı',
      positionLevel: 'Uzman',
      experience: '3-5 yıl deneyim',
      educationLevel: 'Üniversite(Mezun)'
    },
    {
      id: '11',
      title: 'Rezervasyon Elemanı',
      company: 'Swandor Hotels & Resorts',
      location: 'Defterdar Mahallesi, Yeni Küşat Sokak, No:12, Eyüpsultan - İstanbul',
      description: 'SWANDOR TOPKAPI PALACE otelimizde görevlendirilmek üzere aşağıda belirtilen özelliklere sahip  REZERVASYON ELEMANI takım arkadaşları arıyoruz.',
      image: 'https://source.unsplash.com/300x200/?reservation-staff',
      workingHours: '10:00 - 17:00',
      department: 'Satış ve Pazarlama',
      workType: 'Tam Zamanlı',
      positionLevel: 'Eleman',
      experience: '2 yıl deneyim',
      educationLevel: 'Ön Lisans(Mezun), Üniversite(Öğrenci), Üniversite(Mezun), Yüksek Lisans(Öğrenci), Yüksek Lisans(Mezun)'
    }
];

export default jobs;