const userJson = [
    {
      id: '1',
      name: 'Mehmet Baran',
      surname: 'Özdeniz',
      email: 'ozdenizm6@gmail.com',
      password: '12345',
      location: 'İstanbul',
      phoneNumber: '05375959569',
      image: 'https://source.unsplash.com/300x200/?ozdenizm6',
      birthDate: '20.09.2002',
      gender: 'Erkek',
      profession: 'Software Engineering'
    },
    {
      id: '2',
      name: 'Ayşe Nur',
      surname: 'Kaya',
      email: 'aysekaya@gmail.com',
      password: 'abcdef',
      location: 'Ankara',
      phoneNumber: '05451234567',
      image: 'https://source.unsplash.com/300x200/?aysekaya',
      birthDate: '15.05.1995',
      gender: 'Kadın',
      profession: 'Data Science'
    },
    {
      id: '3',
      name: 'Ahmet Can',
      surname: 'Güneş',
      email: 'ahmetgunes@gmail.com',
      password: 'qwerty',
      location: 'İzmir',
      phoneNumber: '05556667777',
      image: 'https://source.unsplash.com/300x200/?ahmetgunes',
      birthDate: '03.12.1988',
      gender: 'Erkek',
      profession: 'UX/UI Design'
    },
    {
      id: '4',
      name: 'Zeynep Demir',
      surname: 'Yılmaz',
      email: 'zeynepyilmaz@gmail.com',
      password: 'zeynep123',
      location: 'Bursa',
      phoneNumber: '05324446688',
      image: 'https://source.unsplash.com/300x200/?zeynepyilmaz',
      birthDate: '10.08.1990',
      gender: 'Kadın',
      profession: 'Digital Marketing'
    },
    {
      id: '5',
      name: 'Mustafa Eren',
      surname: 'Aktaş',
      email: 'erenaktas@gmail.com',
      password: 'mustafa456',
      location: 'Antalya',
      phoneNumber: '05499887766',
      image: 'https://source.unsplash.com/300x200/?erenaktas',
      birthDate: '25.03.1993',
      gender: 'Erkek',
      profession: 'Cybersecurity'
    },
    {
      id: '6',
      name: 'Seda Yılmaz',
      surname: 'Kurt',
      email: 'sedakurt@gmail.com',
      password: 'seda123',
      location: 'Adana',
      phoneNumber: '05553334455',
      image: 'https://source.unsplash.com/300x200/?sedakurt',
      birthDate: '18.07.1985',
      gender: 'Kadın',
      profession: 'Web Development'
    },
    {
      id: '7',
      name: 'Emre Kaya',
      surname: 'Koç',
      email: 'emrekoc@gmail.com',
      password: 'emre789',
      location: 'Trabzon',
      phoneNumber: '05321112233',
      image: 'https://source.unsplash.com/300x200/?emrekoc',
      birthDate: '05.11.1996',
      gender: 'Erkek',
      profession: 'Artificial Intelligence'
    },
    {
      id: '8',
      name: 'Gizem Çetin',
      surname: 'Yıldırım',
      email: 'gizemyildirim@gmail.com',
      password: 'gizem321',
      location: 'Eskişehir',
      phoneNumber: '05446667788',
      image: 'https://source.unsplash.com/300x200/?gizemyildirim',
      birthDate: '30.04.1987',
      gender: 'Kadın',
      profession: 'Graphic Design'
    },
    {
      id: '9',
      name: 'Okan Şahin',
      surname: 'Kaya',
      email: 'okankaya@gmail.com',
      password: 'okan567',
      location: 'Konya',
      phoneNumber: '05334445566',
      image: 'https://source.unsplash.com/300x200/?okankaya',
      birthDate: '12.09.1998',
      gender: 'Erkek',
      profession: 'Mobile App Development'
    },
    {
      id: '10',
      name: 'Elif Demir',
      surname: 'Aydın',
      email: 'elifaydin@gmail.com',
      password: 'elif789',
      location: 'Isparta',
      phoneNumber: '05420001122',
      image: 'https://source.unsplash.com/300x200/?elifaydin',
      birthDate: '22.06.1991',
      gender: 'Kadın',
      profession: 'Product Management'
    }
  ];
  
  export default userJson;
  